amenities_eliminar:
    - college
    - driving_school
    - kindergarten
    - language_school
    - library
    - toy_library
    - music_school
    - school
    - university
    - bicycle_parking
    - bicycle_repair_station
    - bicycle_rental
    - boat_rental
    - boat_sharing
    - bus_station
    - car_rental
    - car_sharing
    - car_wash
    - vehicle_inspection
    - charging_station
    - ferry_terminal
    - fuel
    - grit_bin
    - taxi
    - pharmacy
    - veterinary
    - arts_centre
    - brothel
    - casino
    - cinema
    - community_centre
    - conference_centre
    - events_venue
    - fountain
    - gambling
    - love_hotel
    - nightclub
    - planetarium
    - public_bookcase
    - social_centre
    - stripclub
    - studio
    - swingerclub
    - courthouse
    - embassy
    - fire_station
    - police
    - post_box
    - post_depot
    - prison
    - ranger_station
    - bbq
    - bench
    - dog_toilet
    - drinking_water
    - give_box
    - shelter
    - shower
    - telephone
    - toilets
    - water_point
    - watering_place
    - sanitary_dump_station
    - recycling
    - waste_basket
    - waste_disposal
    - waste_transfer_station
    - animal_boarding
    - animal_breeding
    - animal_shelter
    - baking_oven
    - childcare
    - clock
    - crematorium
    - dive_centre
    - funeral_hall
    - grave_yard
    - gym
    - hunting_stand
    - kitchen
    - kneipp_water_cure
    - lounger
    - marketplace
    - monastery
    - photo_booth
    - place_of_mourning
    - place_of_worship
    - public_bath
    - public_building
    - refugee_site
    - vending_machine
    - user defined


shops_eliminar:
    - department_store
    - mall
